#!/usr/bin/env zsh

export STOW_FOLDERS="i3,bin,nvim,picom,tmux,uwuntu,zsh"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "stow $folder"
    stow -D $folder
    stow $folder
done
popd

